_project_/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path
from todo.views import IndexView, PreView, SaveView, DetailView, DeleteView

app_name = 'todo'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('preview', PreView.as_view(), name='preview'),
    path('preview/<int:id_kinopoisk>', SaveView.as_view(), name='save'),
    path('detail/<int:note_id>', DetailView.as_view(), name='detail'),
    path('detail/<int:note_id>/delete', DeleteView.as_view(), name='delete')
]

todo/models.py
from django.contrib.auth.models import User
from django.db import models


class Movie(models.Model):
    id_kinopoisk = models.IntegerField(unique=True)
    type = models.CharField(max_length=50, blank=True)
    title = models.CharField(max_length=200)
    title_alternative = models.CharField(max_length=200, blank=True, null=True)
    poster = models.URLField(max_length=400)
    directors = models.JSONField(default=[])
    actors = models.JSONField(default=[])
    genres = models.JSONField(default=[])
    countries = models.JSONField(default=[])
    year = models.IntegerField(null=True)
    description = models.TextField(blank=True, null=True)
    slogan = models.CharField(max_length=300, blank=True, null=True)
    age_rating = models.IntegerField(null=True)
    rating_kinopoisk = models.DecimalField(max_digits=6, decimal_places=4, null=True)
    kinopoisk_votes = models.IntegerField(null=True)
    rating_imdb = models.DecimalField(max_digits=6, decimal_places=4, null=True)
    imdb_votes = models.IntegerField(null=True)
    premiere_world = models.DateField(null=True, blank=True, verbose_name='Premiere World')
    premiere_russia = models.DateField(null=True, blank=True, verbose_name='Premiere Russia')
    watchability = models.JSONField(default=[], null=True)
    
    def __str__(self):
        return "%s - %s" % (self.id_kinopoisk, self.title)


class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')
    is_viewed = models.BooleanField(default=False)
    user_rating = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "%s - %s" % (self.user, self.movie.title)

todo/forms.py
from django import forms


class SearchForm(forms.Form):
    id_kinopoisk = forms.CharField(max_length=200, required=True,
                                   widget=forms.TextInput(attrs={'placeholder': 'Enter title film'}))

todo/views.py
import json
import requests

from datetime import datetime
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, View
from envjson import env_str
from todo.forms import SearchForm
from todo.models import Note, Movie


def get_note_list(self):
    try:
        notes_list = Note.objects.all()
    except Note.DoesNotExist:
        return None
    else:
        return notes_list


def get_preview_content(request, field, sort_field):
    search_text = request.POST.get('id_kinopoisk', None)
    token = env_str('KINOPOISK_TOKEN')
    host_api = env_str('KINOPOISK_API_URL')
    limit = env_str('MAX_COUNT_MOVIE_PER_REQUEST')
    if search_text:
        response = requests.get(
            url=f'{host_api}?token={token}&search={search_text}&field={field}'
                f'&sortField={sort_field}&sortType=-1&limit={limit}'
        )
        if response.status_code == 200:
            docs = json.loads(response.content).get('docs')
            content = []
            for item in docs:
                description = item.get('description', None)
                if description is not None:
                    info = {'film': item.get('name'),
                            'year': item.get('year'),
                            'description': description,
                            'poster': get_nested_object(item, 'poster', 'url',
                                                        'https://i.ibb.co/sbw3sB7/no-poster.png'),
                            'id_kinopoisk': item.get('id'),
                            'rating_kp': get_nested_object(item, 'rating', 'kp')}
                    content.append(info)
            return content
        else:
            return {'message': 'Please, check your configuration.'}


def get_detail_film(id_kinopoisk):
    token = env_str('KINOPOISK_TOKEN')
    host_api = env_str('KINOPOISK_API_URL')
    response = requests.get(
        url=f'{host_api}?token={token}&search={id_kinopoisk}&field=id')
    if response.status_code == 200:
        movie = json.loads(response.content)
        persons = movie.get('persons')
        actors = [{item.get('name'): item.get('enName', None)}
                  for item in persons if item['enProfession'] == 'actor'][:15]
        directors = [{item.get('name'): item.get('enName', None)}
                     for item in persons if item['enProfession'] == 'director'][:5]
        content = {'id_kinopoisk': movie.get('id'),
                   'film': movie.get('name'),
                   'film_alternative': movie.get('alternativeName', None),
                   'type': movie.get('type'),
                   'year': movie.get('year', None),
                   'slogan': movie.get('slogan', None),
                   'description': movie.get('description'),
                   'genres': [item.get('name') for item in movie.get('genres')],
                   'age_rating': movie.get('ageRating'),
                   'countries': [item.get('name') for item in movie.get('countries')],
                   'poster': get_nested_object(movie, 'poster', 'url'),
                   'rating_kp': get_nested_object(movie, 'rating', 'kp'),
                   'rating_imdb': get_nested_object(movie, 'rating', 'imdb'),
                   'votes_kp': get_nested_object(movie, 'votes', 'kp'),
                   'votes_imdb': get_nested_object(movie, 'votes', 'imdb'),
                   'premiere_world': get_date_from_iso(movie, 'premiere', 'world'),
                   'premiere_russia': get_date_from_iso(movie, 'premiere', 'russia'),
                   'watchability': get_nested_object(movie, 'watchability', 'items'),
                   'actors': actors,
                   'directors': directors
                   }
        return content
    else:
        return {'message': 'Please, check your configuration.'}


def get_nested_object(content, first_level, second_level, if_missing=None):
    item = content.get(first_level)
    return item.get(second_level) if item else if_missing


def get_date_from_iso(content, first_level, second_level):
    try:
        return datetime.fromisoformat((content.get(first_level).get(second_level))[:-1]).date()
    except TypeError:
        return None


class IndexView(TemplateView):
    template_name = 'todo/index.html'

    def get(self, request, *args, **kwargs):
        return render(request, 'todo/index.html', self.get_context())

    def get_context(self):
        notes = get_note_list(self)
        form = SearchForm()
        context = {'note_list': notes,
                   'form': form}
        return context


class PreView(TemplateView):
    template_name = 'todo/preview.html'

    def post(self, request, *args, **kwargs):
        content = get_preview_content(request, field='name', sort_field='votes.imdb')
        if 'message' in content:
            return render(request, 'todo/error.html', content)
        else:
            return render(request, 'todo/preview.html', {'movies': content})


class DetailView(TemplateView):
    template_name = 'todo/detail.html'

    def get(self, request, *args, **kwargs):
        note = get_object_or_404(Note, pk=kwargs.get('note_id'))
        return render(request, 'todo/detail.html', {'note': note})


class SaveView(View):

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=1)
        content = get_detail_film(kwargs.get('id_kinopoisk'))
        entry_film, _ = Movie.objects.update_or_create(id_kinopoisk=content.get('id_kinopoisk'),
                                                       defaults={
                                                           'title': content.get('film'),
                                                           'title_alternative': content.get('film_alternative'),
                                                           'description': content.get('description'),
                                                           'year': content.get('year'),
                                                           'poster': content.get('poster'),
                                                           'rating_kinopoisk': content.get('rating_kp'),
                                                           'type': content.get('type'),
                                                           'slogan': content.get('slogan'),
                                                           'genres': content.get('genres'),
                                                           'age_rating': content.get('age_rating'),
                                                           'countries': content.get('countries'),
                                                           'rating_imdb': content.get('rating_imdb'),
                                                           'kinopoisk_votes': content.get('votes_kp'),
                                                           'imdb_votes': content.get('votes_imdb'),
                                                           'premiere_world': content.get('premiere_world'),
                                                           'premiere_russia': content.get('premiere_russia'),
                                                           'watchability': content.get('watchability'),
                                                           'actors': content.get('actors'),
                                                           'directors': content.get('directors')
                                                       })
        Note.objects.update_or_create(user=user, movie=entry_film)
        return redirect('todo:index')


class DeleteView(View):

    def post(self, request, *args, **kwargs):
        note = get_object_or_404(Note, pk=kwargs.get('note_id'))
        if note:
            note.delete()
        return redirect('todo:index')

_project_/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Film Todo</title>
    <style>
       li {
        list-style-type: none;
       }
       .search-block {
           text-align: center;
       }
       .note_list {
           text-align: center;
       }
  </style>
</head>
<body>
{% block content %}{% endblock %}
{% block note %}{% endblock %}
{% block detail %}{% endblock %}
{% block error %}{% endblock %}
</body>
</html>

_project_/templates/todo/detail.html
{% extends 'todo/base.html' %}

{% block detail %}
    <div class="container">
        <form action="{% url "todo:delete" note.id %}" method="post">
            {% csrf_token %}
            <h1>{{ note.movie.title }} / {{ note.movie.title_alternative }}</h1>
            <div>
                <img src="{{ note.movie.poster }}" width="332" height="500" alt="{{ note.movie.title }}">
                <h3>Year: {{ note.movie.year }}</h3>
                <h3>Rating by kinopoisk: {{ note.movie.rating_kinopoisk }}</h3>
                <h4>Slogan: {{ note.movie.slogan }} </h4>
                <h4>Age rating: {{ note.movie.age_rating }}</h4>
                <h4>Genres: {{ note.movie.genres|join:", " }}</h4>
                <h4>Countries: {{ note.movie.countries|join:", " }}</h4>
                <h4>Premiere world: {{ note.movie.premiere_world }}</h4>
                <h4>Directors: {{ note.movie.directors|join:", " }}</h4>
                <h4>Actors: {{ note.movie.actors|join:", " }}</h4>
                <p>{{ note.movie.description }}</p>
            </div>
            <a href="{{request.META.HTTP_REFERER}}">Go back</a>
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

_project_/templates/todo/error.html
{% extends 'todo/base.html' %}

{% block error %}
    <div class="container">
        <h1>{{ message }}</h1>
        <a href="{{request.META.HTTP_REFERER}}">Go back</a>
    </div>
{% endblock %}

_project_/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block content %}
    {% block search_block %}
        <div class="container">
            <div class="search-block">
                <h1>Find your film here</h1>
                <form action="{% url "todo:preview" %}" method="post">
                    {% csrf_token %}
                    {{ form.id_kinopoisk }}
                    <button type="submit">Search</button>
                </form>
            </div>
        </div>
    {% endblock %}
    {% block note_list %}
        {% if note_list %}
            <div class="note_list">
                <h2>A list with your saved movies</h2>
            </div>
        <section id="todo_list">
            <div class="container">
                <form action="{% url "todo:index" %}" method="get">
                {% csrf_token %}
                    <div class="row">
                        <ul>
                            {% for item in note_list %}
                                <li>
                                    <div class="menu-desc text-center">
                                        <hr>
                                        <h3>{{ item.movie.title }}</h3>
                                            <div>
                                                <img src="{{ item.movie.poster }}" width="165" height="250" alt="{{ item.movie.title }}">
                                                <h3>Year: {{ item.movie.year }}</h3>
                                                <p>Description: {{ item.movie.description }}</p>
                                                <a href="/detail/{{ item.id }}">Detail about note</a>
                                            </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </form>
            </div>
        </section>
    {% endif %}
    {% endblock %}
{% endblock %}

_project_/templates/todo/note.html
{% extends 'todo/base.html' %}

{% block note %}
    <div class="container">
        <form action="{% url "todo:index" %}" method="post">
            {% csrf_token %}
            <h2>{{ film }}</h2>
            <a href="{{request.META.HTTP_REFERER}}">Go back</a>
            <button type="submit">Add to the list</button>
            <div>
                <img src="{{ poster }}" width="332" height="500" alt="{{ film }}">
                <h2>Year: {{ year }}</h2>
                <p>Description: {{ description }}</p>
            </div>
        </form>
    </div>
{% endblock %}

_project_/templates/todo/preview.html
{% extends 'todo/base.html' %}

{% block note %}
    <div class="container">
        <a href="{{request.META.HTTP_REFERER}}">Go back</a>
        <div class="row">
            <ul>
                {% for item in movies %}
                {% csrf_token %}
                <li>
                    <div class="menu-desc text-center">
                        <hr>
                        <h3>{{ item.film }}</h3>
                            <div>
                                <img src="{{ item.poster }}" width="165" height="250" alt="{{ item.film }}">
                                <h3>Year: {{ item.year }}</h3>
                                <h4>Rating: {{ item.rating_kp }}</h4>
                                <p>Description: {{ item.description }}</p>
                            </div>
                    </div>
                </li>
                    <a href="/preview/{{ item.id_kinopoisk }}">Add to the list</a>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}